# Generated by Django 3.0.8 on 2020-07-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_username', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('post_message', models.CharField(max_length=600)),
                ('post_likes', models.CharField(max_length=600)),
                ('post_comments', models.CharField(max_length=600)),
            ],
        ),
    ]
