# Generated by Django 3.0.8 on 2020-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_user_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
