# Generated by Django 3.0.8 on 2020-08-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.IntegerField(max_length=11),
        ),
    ]
