# Generated by Django 3.0.8 on 2020-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200822_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='username_id',
            field=models.IntegerField(max_length=11),
        ),
    ]
